[apache]
10.0.0.182 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/migration_key

[backup]
10.0.0.134 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/migration_key

[ftp]
10.0.0.116 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/migration_key

[mariadb]
10.0.0.118 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/migration_key

[nfs]
10.0.0.143 ansible_user=ubuntu ansible_ssh_private_key_file=/home/user/.ssh/migration_key

